#!python
from user_interface import UserInterface
import curses
import signal
import os

def signal_handler(signal, frame):
    pass

# Intercept ctrl-c, ctrl-\ and ctrl-z
signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGQUIT, signal_handler)
signal.signal(signal.SIGTSTP, signal_handler)

# Lower the annoying delay for the escape character
# VIM also uses 25 ms
os.environ['ESCDELAY'] = '25'

ui = UserInterface()
curses.wrapper(ui.main)
